routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FilmsController;
use App\Http\Controllers\CommentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/films');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
  
Route::resource('films', FilmsController::class, ['except' => [
    'show'
]]);

Route::get('/films/{slug}', [FilmsController::class, 'show'])->name('films.show');

Route::resource('comments', CommentController::class);

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

use DB;

class Film extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'description', 'slug', 'release_date', 'rating', 'ticket_price', 'country', 'photo'
    ];

     /**
     * The genres that belong to the film.
     */
    public function genres() {
        return $this->belongsToMany(Genre::class);
    }

    /**
     * The has Many Relationship
     *
     * @var array
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * Get all records of films with genres in storage.
     *
     * @return array
     */
    public function get_all_films(){

        $films = Film::with('genres:genre')->latest()->paginate(9);

        return $films;
    }
    
    /**
     * Boot the model.
     */
    protected static function boot()
    {
        parent::boot();
  
        static::created(function ($film) {
            $film->slug = $film->createSlug($film->name);
            $film->save();
        });
    }

    /** 
     * Create unique slug
     *
     * @return response()
     */
    private function createSlug($name){
        if (static::whereSlug($slug = Str::slug($name))->exists()) {
            $max = static::whereName($name)->latest('id')->skip(1)->value('slug');
  
            if (is_numeric($max[-1])) {
                return preg_replace_callback('/(\d+)$/', function ($mathces) {
                    return $mathces[1] + 1;
                }, $max);
            }
  
            return "{$slug}-2";
        }
  
        return $slug;
    }
}

app/Http/Controllers/API/V1/FilmController.php
<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use App\Models\Film;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Resources\FilmResource;

class FilmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $films = Film::with('genres:genre')->get();
        return response([ 'films' => FilmResource::collection($films), 'message' => 'Retrieved successfully'], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $data = $request->all();

        // validate the posted input fields submitted by user end using form
        $validator = Validator::make($data, [
            'name' => 'required',
            'description' => 'required',
            'rating' => 'required',
            'ticket_price' => 'required',
            'country' => 'required',
            'release_date' => 'required',
            'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'genres' => 'required'
        ]);
        
        if ($validator->fails()) {
            return response(['error' => $validator->errors(), 'Validation Error']);
        }

        // image uploader
        if ($request->hasFile('photo')) {
            $fileName = time().'_'.$request->file('photo')->getClientOriginalName();
            
            $filePath = $request->file('photo')->storeAs('uploads', $fileName, 'public');

            $fileNameToStore = '/storage/' . $filePath;
            
        }
        else {
            $fileNameToStore = 'noimage.jpg';
        }

        $str = strtolower($request->name);
        $slug = preg_replace('/\s+/', '-', $str);
        
        $data['photo'] = $fileNameToStore;
        $data['slug'] = $slug;

        // insert posted data into database
        $film = Film::create($data);

        // attach genre to film
        foreach($request->genres as $genre){
            $film->genres()->attach($genre);
        }

        return response(['film' => new FilmResource($film), 'message' => 'Created successfully'], 201);
    }

    /**
     * Display the specified film.
     *
     * @param  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {   
        $film = Film::with('genres', 'comments')->where('slug', '=', $slug)->first();
        return response(['film' => new FilmResource($film), 'message' => 'Retrieved successfully'], 200);
    } 

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Film  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Film $film)
    {
        $film->delete();

        return response(['message' => 'Deleted']);
    }
}

app/Http/Controllers/FilmsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Film;
use App\Models\Genre;

use Illuminate\Support\Str;

class FilmsController extends Controller
{
   /**
     * Display a listing of the film.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $filmObj = new Film();

        $films = $filmObj->get_all_films();
     
        return view('films.index',compact('films'))
            ->with('i', (request()->input('page', 1) - 1) * 9);
    }

    /**
     * Show the form for creating a new film.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genres = Genre::all();
        return view('films.create', compact('genres'));
    }

    /**
     * Store a newly created film in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        // making slug
        $str = strtolower($request->name);
        $slug = preg_replace('/\s+/', '-', $str);
        
        // validate the posted input fields submitted by user end using form
        $request->validate([
            'name' => 'required',
            'description' => 'required',
            'rating' => 'required',
            'ticket_price' => 'required',
            'country' => 'required',
            'release_date' => 'required',
            'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg',
            'genres' => 'required'
        ]);

        // image uploader
        if ($request->hasFile('photo')) {
            $fileName = time().'_'.$request->file('photo')->getClientOriginalName();
            
            $filePath = $request->file('photo')->storeAs('uploads', $fileName, 'public');

            $fileNameToStore = '/storage/' . $filePath;
            
        }
        else {
            $fileNameToStore = 'noimage.jpg';
        }
        
        $requestData = $request->all();
        $requestData['photo'] = $fileNameToStore;
        $requestData['slug'] = $slug;

        // insert posted data into database
        $film = Film::create($requestData);

        // attach genre to film
        foreach($request->genres as $genre){
            $film->genres()->attach($genre);
        }
        
        return redirect()->route('films.index')
                        ->with('success','Film created successfully.');
    }

    /**
     * Display the specified film.
     *
     * @param  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {   
        $film = Film::with('genres:genre')->where('slug', '=', $slug)->first();

        return view('films.show',compact('film'));
    } 
     
    /**
     * Show the form for editing the specified film.
     *
     * @param  \App\Models\Film  $film
     * @return \Illuminate\Http\Response
     */
    public function edit(Film $film)
    {
        return view('films.edit',compact('film'));
    }
    
    /**
     * Update the specified film in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Film  $film
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Film $film)
    {
        $request->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);
    
        $product->update($request->all());
    
        return redirect()->route('films.index')
                        ->with('success','Film updated successfully');
    }
    
    /**
     * Remove the specified film from storage.
     *
     * @param  \App\Models\Film  $film
     * @return \Illuminate\Http\Response
     */
    public function destroy(Film $film)
    {
        $film->delete();
    
        return redirect()->route('films.index')
                        ->with('success','Film deleted successfully');
    }
}

resources/views/films/comments.blade.php
@foreach($comments as $comment)
    <div class="display-comment">
        {{-- <strong>{{ $comment->user->name }}</strong> --}}
        <strong>{{ $comment->name }}</strong>
        <p>{{ $comment->comments }}</p>
    </div>
    <hr />
@endforeach

resources/views/films/create.blade.php
@extends('layouts.app')
  
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('films.index') }}"> Back</a>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="">
                            <div class="card-header">{{ __('Add New Film') }}</div>
                        </div>
                    </div>
                </div>
   
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                
                <div class="card-body">
                    <form action="{{ route('films.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                    
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    <input type="text" name="name" class="form-control" placeholder="Name" value="{{ old('name') }}">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Country:</strong>
                                    <select id="country" name="country" class="form-control">
                                        <option value="United Kingdom">United Kingdom</option>
                                        <option value="United States">United States</option>
                                        <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
                                        <option value="Uruguay">Uruguay</option>
                                        <option value="Uzbekistan">Uzbekistan</option>
                                        <option value="Vanuatu">Vanuatu</option>
                                        <option value="Venezuela">Venezuela</option>
                                        <option value="Viet Nam">Viet Nam</option>
                                        <option value="Virgin Islands, British">Virgin Islands, British</option>
                                        <option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
                                        <option value="Wallis and Futuna">Wallis and Futuna</option>
                                        <option value="Western Sahara">Western Sahara</option>
                                        <option value="Yemen">Yemen</option>
                                        <option value="Zambia">Zambia</option>
                                        <option value="Zimbabwe">Zimbabwe</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>rating:</strong>
                                    <select class="form-control" name="rating">
                                        <option value="1" {{ (old("rating") == 1 ? "selected":"") }}>1</option>
                                        <option value="2" {{ (old("rating") == 2 ? "selected":"") }}>2</option>
                                        <option value="3" {{ (old("rating") == 3 ? "selected":"") }}>3</option>
                                        <option value="4" {{ (old("rating") == 4 ? "selected":"") }}>4</option>
                                        <option value="4" {{ (old("rating") == 5 ? "selected":"") }}>5</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Ticket Price:</strong>
                                    <input type="text" name="ticket_price" class="form-control" placeholder="95" value="{{ old('ticket_price') }}">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Release Date:</strong>
                                    <div class='input-group date' id='datepicker'>
                                    <input name="release_date" type='text' class="form-control" value="{{ old('release_date') }}" />
                                    <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                    </div>
                                </div>
                            </div>
                            @if($genres)
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Select Genres(you can choose multiple generes):</strong>
                                        <select name="genres[]" multiple="multiple">
                                            @foreach ($genres as $genre)
                                                <option value="{{ $genre->id }}">{{ $genre->genre }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            @endif
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Description:</strong>
                                    <textarea class="form-control" style="height:150px" name="description" placeholder="Detail">{{ old('description') }}</textarea>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Image:</strong>
                                    <input type="file" name="photo" id="">
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8"><br />
                                        <button type="submit" class="btn btn-lg btn-primary">Submit</button>
                                        {{-- <div class="pull-right"> --}}
                                            <a class="btn btn-lg btn-danger" href="{{ route('films.index') }}"> Cancel</a>
                                        {{-- </div> --}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $('#datepicker').datepicker({  
       format: 'yyyy-mm-dd'
     });  
</script> 
@endsection

resources/views/films/edit.blade.php
@extends('films.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Film</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('films.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('films.update',$film->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $film->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail">{{ $film->detail }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/films/index.blade.php
@extends('layouts.app')

<style>
    img {
        border: 1px solid #ddd; /* Gray border */
        border-radius: 4px;  /* Rounded border */
        padding: 5px; /* Some padding */
        width: 150px; /* Set a small width */
    }

    /* Add a hover effect (blue shadow) */
    img:hover {
        box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
    }

    .btn-info {
        color: #fff !important;
        background-color: #5bc0de;
        border-color: #46b8da;
    }

    p.genres{
        line-height: 1px;
        font-size: 13px;
        font-weight: bold;
        color: red;
        display: block;
    }
    p.description{
        display: block;
        padding-top: 14px;
    }
    .card-img-top {
        width: 100%;
        height: 26vw;
        object-fit: cover;
    }
</style>
 
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('films.create') }}"> Create New Film</a>
            </div>
        </div>
        <div class="col-md-12">
            
                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="">
                            <div class=""><h2>{{ __('Films Listing') }}</h2></div>
                        </div>
                    </div>
                </div>
   
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    <div class="row">
                    @if(!$films->isEmpty())
                        @foreach ($films as $film)
                        <div class="col-4">
                            <div class="card">
                                <div class="card-header">Release Date: <b>{{ $film->release_date }}</b></div>

                                <a class="" href="{{ route('films.show',$film->slug) }}">
                                    <div class="bg-image hover-zoom">
                                        {!! Html::image($film->photo, $film->name, array('class' => 'card-img-top w-100')) !!}
                                    </div>
                                </a>
                
                                <div class="card-body">
                                <h5 class="card-title">{{ $film->name }}</h5>
                                <div class="pull-right">
                                </div>
                                <p class="genres">{{ \Illuminate\Support\Str::limit($film->genres->pluck('genre')->implode(', '), 32, $end='...') }}</p>
                                <p class="card-text description">
                                {{ \Illuminate\Support\Str::limit($film->description, 32, $end='...') }}
                                </p>
                                <span class="pull-right">Ticket Price: <b>${{ $film->ticket_price }}</b></span>
                                <span class="pull-left">Rating: <b>{{ $film->rating }}</b></span>
                                </div>
                                <div class="card-footer text-muted"><a class="btn btn-outline-info btn-md btn-block" href="{{ route('films.show',$film->slug) }}">Visit</a></div>
                                {{-- <form action="{{ route('films.destroy',$film->id) }}" method="POST">
                    
                                    <a class="btn btn-info" href="{{ route('films.show',$film->slug) }}">Show</a>
                    
                                    <a class="btn btn-primary" href="{{ route('films.edit',$film->id) }}">Edit</a>
                
                                    @csrf
                                    @method('DELETE')
                    
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form> --}}
                            </div>
                        
                        </div>
                        @endforeach
                    @else
                        <div class="col-12 text-center"><h2>No record found!</h2></div>
                    @endif
                </div>

                {!! $films->links() !!}
            
        </div>
    </div>
</div>

@endsection

resources/views/films/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 8 CRUD Application - ItSolutionStuff.com</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>

resources/views/films/show.blade.php
@extends('layouts.app')
  
@section('content')

<style>
    p.genres{
        line-height: 1px;
        font-size: 13px;
        font-weight: bold;
        color: red;
        display: block;
    }
    p.description{
        display: block;
        padding-top: 14px;
    }
    .card-img-top {
        width: 100%;
        height: 30vw;
        object-fit: cover;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('films.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card">
                <div class="card-header">
                    <span class="pull-left">Released: <b>{{ $film->release_date }}</b></span>
                    <span class="pull-right">Country: <b>{{ $film->country }}</b></span>
                </div>

                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                    {!! Html::image($film->photo, $film->name, array('class' => 'card-img-top')) !!}
                    <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                    </a>
                </div>

                <div class="card-body">
                  <h5 class="card-title">{{ $film->name }}</h5>
                  <div class="pull-right">
                  </div>
                  <p class="genres">{{ $film->genres->pluck('genre')->implode(', ') }}</p>
                  <p class="card-text description">
                  {{ \Illuminate\Support\Str::limit($film->description, 200, $end='...') }}
                  </p>
                  <span class="pull-right">Ticket Price: <b>${{ $film->ticket_price }}</b></span>
                  <span class="pull-left">Rating: <b>{{ $film->rating }}</b></span>
                </div>
            </div>

            <div class="card">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                  {{-- <h5 class="card-title">Display Comments</h5> --}}
                  <p class="card-text">
                    @include('films.comments', ['comments' => $film->comments, 'film_id' => $film->id])
                  </p>
                  
                  <h4>Add comment</h4>
                  <form method="post" action="{{ route('comments.store') }}">
                      @csrf
                      <div class="form-group">
                          <input class="form-control" type="text" name="name" placeholder="name">
                      </div>
                      <div class="form-group">
                          <textarea class="form-control" name="comments"></textarea>
                          <input type="hidden" name="film_id" value="{{ $film->id }}" />
                      </div>
                      <div class="form-group">
                          <input type="submit" class="btn btn-success" value="Add Comment" />
                      </div>
                  </form>
                </div>
              </div>
        </div>
    </div>
</div>
   
 
@endsection